experiment:
  seed: 12
  device: cuda
  expt_name: dino_vit_base # experiment name
  log_freq: 20 # knn accuracy is computed every `log_freq` epochs, additionally the trained model is also saved
  output_dir: ./working/dino_vit_base # output results to this folder - files: logs.txt, {experiment_name}_models
  ssl_training: dino # training strategy to use
  use_mixed_precision: true # if true uses fp16 for training, improves training speed
# input image parameters
input:
  channels: 3 # num channels in input image
  data path: ./input/reallensdataset/real_lenses_dataset # path/to/dataset
  indices: ./input/reallenses-traintestindices/indices.pkl
  image size:
  - 32 # image height to perform center crop
  - 32 # image width to perform center crop
  num classes: 2
# training network parameters
network:
  backbone: vit_base # backbone network
  head_bottleneck_dim: 192
  head_hidden_dim: 256
  head_nlayers: 3
  head_norm_last_layer: true
  head_output_dim: 512
  head_use_bn: true
  patch_size: 8
  use_dense_prediction: false
  window_size: None
  ape: None
  use_L1: false
optimizer:
  init_lr: 0.00005
  init_wd: 0.001
  final_lr: 0.00000005
  final_wd: 0.001
  momentum_teacher: 0.996
  optimizer: AdamW
  scheduler_warmup_epochs: 10
  teacher_temp: 0.04
  warmup_teacher_temp: 0.04
  warmup_teacher_temp_epochs: 0
  clip_grad_magnitude: 0.
# restart training from checkpoint file ckpt
restore:
  ckpt_path: null # path/to/ckpt
  restore: false # if true, restart from provided ckpt
# keyword args for the ssl per data augmentation
ssl augmentation kwargs:
  augmentation: AugmentationDINOSingleChannel
  center_crop: 32
  global_crop_scale_range:
  - 0.14
  - 1.0
  global_crop_size: 32
  local_crop_scale_range:
  - 0.01
  - 0.14
  local_crop_size: 20
  num_local_crops: 16
# training parameters
train args:
  knn_neighbours: 20
  batch_size: 128
  num_epochs: 100
  freeze_last_layer: 0
  train_val_split:
  - 0.85
  - 0.15

